# Generated by Django 4.2.3 on 2023-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('projects', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('happy_clients', models.CharField(max_length=200)),
                ('customers', models.CharField(max_length=200)),
            ],
        ),
    ]
