# Generated by Django 4.2.3 on 2023-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_blog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
