# Generated by Django 4.2.3 on 2023-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_botuser_feedback_alter_blog_img_alter_portfolio_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='body',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
