# Generated by Django 4.2.3 on 2023-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='google',
            new_name='project_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='telegram',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
