# Generated by Django 4.2.3 on 2023-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_rename_google_portfolio_project_url_remove_blog_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
