# Generated by Django 4.2.3 on 2023-08-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_portfolio_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='img',
            new_name='photo',
        ),
    ]
